### ISSUE TITLE
`platform self:install` doesn't properly detect shell

### ISSUE THREAD

**Issue by hanoii** [platformsh/cli#117]
I think the issue is that the platform doesn't get the SHELL env var properly or populate within the child process or the like:

I am inside a ddev container:

```
$ echo $SHELL
/bin/bash
```

```
$ platform self:install
...
Setting up autocompletion... skipped (unsupported shell)
...
```

```
$ SHELL=$SHELL platform self:install -vvv
...
DEBUG Detected shell type: bash
Setting up autocompletion...# Running subcommand: _completion --generate-hook=1 --program=platform --shell-type=bash
 done
...
```

**Comment by pjcdawkins** [comment]
Hm, @akalipetis I thought we were sending the entire environment to the child process like this -

https://github.com/platformsh/cli/blob/5f1fdf6006435c621cb1c01f8d50e21caafcce1e/internal/legacy/legacy.go#L159

**Comment by akalipetis** [comment]
Yes, we do. That's quite strange and needs a bit of debugging, maybe the way `os.Environ()` works is not the one we believe? 😕

**Comment by hanoii** [comment]
This is not an issue on `platform cli`, see https://github.com/ddev/ddev/issues/6018.
