### ISSUE TITLE
Use proper XDG configuration folders instead of just HOME

### ISSUE THREAD

**Issue by shyim** [platformsh/cli#148]
```
 # BEGIN: Upsun certificate configuration
Host *.platform.sh *.upsun.com
  Include /Users/shyim/.upsun-cli/ssh/*.config
Host *
# END: Upsun certificate configuratio
```

The complete `.upsun-cli` folder should be at `~/Library/Application\ Support/upsun-cli`

See https://pkg.go.dev/os#UserConfigDir

**Comment by akalipetis** [comment]
@shyim thanks for reporting. We could definitely do something like this, but given that we currently have a rather complex setup with our [Legacy CLI](https://github.com/platformsh/legacy-cli) and new functionality working side-by-side here, we've decided not to touch on configuration directories for now.

If you'd like, you can still choose your configuration directory with the following environment variable:

```console
export UPSUN_CLI_APPLICATION_USER_CONFIG_DIR=Application\ Support/upsun-cli
```

If you need this at all times, you can add this to your `.zshrc`/`.bashrc` files as well.

**Comment by shyim** [comment]
Maybe leave this issue open with a label so it won't get lost. I hope the legacy cli will be removed 🙈
