### ISSUE TITLE
Ensure the right version is used in the API user-agent

### ISSUE THREAD

**Issue by lolautruche** [platformsh/cli#161]
It seems that it's still the legacy user-agent that is used when consuming the API (v4 legacy).

**Comment by akalipetis** [comment]
The user agent is sent correctly, it contains both the Legacy CLI version and the Wrapper version (which are not different).
Ref: https://github.com/platformsh/cli/blob/e9fd86d6cd9b1e07fb1a82d6480b2adfd8aa58ca/internal/legacy/legacy.go#L173-L179
