### ISSUE TITLE
Wrapped legacy CLI version shown as 0.0.0

### ISSUE THREAD

**Issue by akalipetis** [platformsh/cli#20]
```console
platform --version
Platform.sh CLI 4.0.0 (Wrapped legacy CLI 0.0.0)
```

This is not expected, the correct Legacy CLI version should be shown there.

_Originally posted by @lolautruche in https://github.com/platformsh/cli/issues/18#issuecomment-1374012064_

**Comment by pjcdawkins** [comment]
Fixed by #21 I assume
