### ISSUE TITLE
Choose a better name than 'platform' for the installed package

### ISSUE THREAD

**Issue by gggeek** [platformsh/cli#30]
When installing the psh cli via the .deb file, it ends up known as "platform" (as seen by running eg `dpkg --list`).

I think that name is highly confusing, being way too generic and broad. what about "platformsh-cli" instead?

**Comment by akalipetis** [comment]
We should better go with `platformsh-cli`, as this is the name we use in most places - the binary. What do you think @lolautruche?

**Comment by lolautruche** [comment]
I agree @akalipetis .
