### ISSUE TITLE
CLI on Mac M2

### ISSUE THREAD

**Issue by MarkusH12** [platformsh/cli#36]
Running the platform cli on a Mac M2 laptop brings the following error

dyld[13237]: Library not loaded: /opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: <B0991961-C77E-3643-A497-95DE733E892F> /private/var/folders/37/zhd2lcr5381d870hz83ypxx00000gn/T/psh-go-8.0.27-4.0.2/php-8.0.27
  Reason: tried: '/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file, not in dyld cache)

**Comment by akalipetis** [comment]
Thanks for reporting @MarkusH12 - have you installed the CLI using HomeBrew? This error seems like it's coming from an installation where the binary was installed as a standalone.

If it was installed using HomeBrew, could you please send us the output of the following commands?

```console
which platform
brew --prefix
```

Thanks!

**Comment by MarkusH12** [comment]
Yes, I installed it with homebrew.

which platform
/usr/local/bin/platform

brew --prefix
/usr/local

**Comment by akalipetis** [comment]
It's exactly what @rfay mentioned, although we're looking into ways to make this work even for ported installation prefixes.

Keeping this open to track this effort.

**Comment by rfay** [comment]
I would love to find a way to help people avoid this horrendous homebrew problem, which has been in progress for 2 years now. It has tripped so many people. I'm not sure how to do it in an unobtrusive manner. A way to avoid this problem in the first place is to turn off Rosetta, but Rosetta can be mighty nice for some traditional apps, but it's a disaster on the command-line with per-architecture binaries.

**Comment by MarkusH12** [comment]
That's it, thank you very much. I switched from an "old" Mac. Seems like the homebrew installation was taken over.

Thank you all for the quick help

**Comment by akalipetis** [comment]
It's great to hear this @MarkusH12 - keeping this open to track the issue in case we find a better solution.

**Comment by akalipetis** [comment]
@MarkusH12 I'm going to close this one, as this issue should not exist starting with version `4.6.1`, following https://github.com/platformsh/cli/pull/62

If you face this issue again, feel free to get back to us!
