### ISSUE TITLE
inconsistent versions in release artifact

### ISSUE THREAD

**Issue by daeMOn63** [platformsh/cli#6]
Hello! Looking at the artifacts' version from https://github.com/platformsh/cli/releases/tag/4.0.0-rc.3, there seems to be 3 different formats in use:
```
4.0.0-rc.3
4.0.0.rc.3
4.0.0rc.3
```

Would it be possible to have a single one, ideally matching the `4.0.0-rc.3` tag format, to ease scripting ?

**Comment by akalipetis** [comment]
Fixed in 2a683cf88cce3b3420c602981710b200ddea879f
