### ISSUE TITLE
Invite users to run `brew update` before `brew upgrade`

### ISSUE THREAD

**Issue by lolautruche** [platformsh/cli#68]
When a new version is detected, we display a message urging the user to upgrade the CLI to new version.
However, due to Homebrew upgrade mechanism, it's usually advised to run `brew update` before upgrading a program using a 3rd party tap.

Otherwise, it leads to such issues:
![CleanShot 2023-05-26 at 15 46 23@2x](https://github.com/platformsh/cli/assets/313528/6b7bc05e-7970-43f9-862c-0335cb0ddf1a)

We should invite the user to run `brew update && brew upgrade platformsh-cli`

**Comment by gedw99** [comment]
i got an error :

``` 
brew install platformsh-cli
==> Downloading https://formulae.brew.sh/api/formula.jws.json
################################################################################################################ 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
################################################################################################################ 100.0%
Warning: No available formula with the name "platformsh-cli". Did you mean platformio?
==> Searching for similarly named formulae and casks...
==> Formulae
platformio

To install platformio, run:
  brew install platformio
```

**Comment by lolautruche** [comment]
Hi @gedw99 
You need to run `brew install platformsh/tap/platformsh-cli`, or add the tap before installing `platformsh-cli` :)
