### ISSUE TITLE
Cli issue on RH7.9

### ISSUE THREAD

**Issue by cyril-ext** [platformsh/cli#71]
Hello,

The platform sh support asks me to create an issue here (https://support.platform.sh/hc/en-us/requests/239416).
On Red Hat Enterprise Linux Server release 7.9 (Maipo), the platform sh cli has no input.

The installation seems to be ok :

Log of the installation using curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | bash :
^[[1;33m+--------------------------------------------------+^[[22;39m
^[[1;33m| |^[[22;39m
^[[1;33m| Platform.sh CLI Installer |^[[22;39m
^[[1;33m| |^[[22;39m
^[[1;33m+--------------------------------------------------+^[[22;39m
^[[1;33m
Checking environment^[[22;39m
^[[0;32m [*] Your kernel (linux) is supported^[[0m
^[[0;32m [*] Your architecture (amd64) is supported^[[0m
^[[0;32m [*] Using raw install method^[[0m
^[[0;32m [*] cURL is installed^[[0m
^[[0;32m [*] No version specified, using latest (4.6.1)^[[0m
^[[0;32m [*] Gzip is installed^[[0m
^[[0;32m [*] sha1sum is installed^[[0m
^[[0;32m [*] /usr/bin is in $PATH^[[0m
^[[1;33m
Target directories^[[22;39m
Binary will be installed in /usr/bin
^[[1;33m
Downloading the Platform.sh CLI^[[22;39m
Downloading https://github.com/platformsh/cli/releases/download/4.6.1/platform_4.6.1_linux_amd64.tar.gz
Uncompressing archive
Making the binary executable
Installing the binary under /usr/bin

^[[0;32m+--------------------------------------------------+^[[0m
^[[0;32m| |^[[0m
^[[0;32m| Platform.sh CLI has been installed successfully. |^[[0m
^[[0;32m| |^[[0m
^[[0;32m+--------------------------------------------------+^[[0m
^[[1;33m
What's next?^[[22;39m
To use the CLI, run: platform
^[[1;33m
Useful links:^[[22;39m
CLI introduction: https://docs.platform.sh/get-started/introduction.html#cli

As root : ls -l /usr/bin/platform
-rwxr-xr-x 1 501 games 28344320 26 mai   15:26 /usr/bin/platform

/usr/bin/platform -vvv return nothing.

Regards.

**Comment by akalipetis** [comment]
Hey, @cyril-ext - thanks for reporting this issue. I tried to reproduce it on CentOS 7.9 but couldn't. Please let us know if you have any specific security rules that might affect this.

For example, can you explicitly give it a temporary directory that is writable and run Platform.sh again? You can do this with the following command:
```console
TMPDIR=/something/writable platform
```

**Comment by cyril-ext** [comment]
Hello,

We have install the goland cli and the cli return a timetout. We know how to solve it (flow issue).

Thanks.

**Comment by akalipetis** [comment]
That's good to hear @cyril-ext - I'm going to solve this one for now, but please come back here in case you still face issues.
