### ISSUE TITLE
When generating .environment using Platformify, wrap string values in quotes

### ISSUE THREAD

**Issue by tylers-username** [platformsh/cli#97]
When generating the `.environment` from Platformify for, let's say Node.js, you might get a line like:

```bash
export RELATIONSHIPS_JSON=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode)
```

`dash .environment` in this case will throw the error, which will prevent a deployment activity from completing as well as blocking the `web.commands.start`:

> `.environment: 1: export: [{"username":: bad variable name`

## Fix
Wrap the string in quotes:

```bash
export RELATIONSHIPS_JSON="$(echo $PLATFORM_RELATIONSHIPS | base64 --decode)"
```

It may be useful to take this a step further and wrap `$PLATFORM_RELATIONSHIPS` or, in other cases, `$PLATFORM_ROUTES` in quotes as well to prevent word splitting. e.g. `echo hello world` vs `echo "hello world"`.

```bash
export RELATIONSHIPS_JSON="$(echo "$PLATFORM_RELATIONSHIPS" | base64 --decode)"
```

**Comment by akalipetis** [comment]
This is already resolved in the Platformify library and will be released alongside the next release of the library. Keeping this open until it happens.
