### ISSUE TITLE
CLI 4.8.0 - broken SSH

### ISSUE THREAD

**Issue by Vormillion** [platformsh/cli#98]
Hello,

After latest upgrade to version 4.8.0 we've found strange issue in platform ssh command. Everything was working in 4.7.0.

We are invoking command like this:
`platform ssh -p XXX -e PR-1614 'php bin/magento config:set --lock-env --scope websites --scope-code base web/secure/base_url xxx.com'`

As you can see, SSH command is in single quotes. On 4.8.0 it started throwing errors:
`/bin/bash: php bin/magento config:set --lock-env --scope websites --scope-code base web/secure/base_url xxx.com: No such file or directory
Connection to ssh.eu-4.platform.sh closed.`

When we will change single quotes to double quotes everything works fine on 4.8.0.
Is it intended behaviour?

```[tasklist]
### Tasks
```

**Comment by akalipetis** [comment]
This has been fixed with #99
